image: "rust:latest"

stages:
  - build
  - test
  - sast
  - semgrep
  - sonarcloud


build:
  stage: build
  script:
    - cargo check
    - cargo build -r

test:
  stage: test
  script:
    - rustc --version && cargo --version 
    - cargo test --workspace --verbose

sast:
  stage: sast
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml

semgrep:
  stage: semgrep
  image: semgrep/semgrep
  script: semgrep ci --code
  variables:
    SEMGREP_APP_TOKEN: "$SEMGREP_APP_TOKEN"


sonarcloud:
  stage: sonarcloud
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.organization="$ORGANIZATION" -Dsonar.projectKey="$PROJECTKEY"
  variables:
    SONAR_HOST_URL: "$SONAR_HOST_URL"
    SONAR_TOKEN: "$SONAR_TOKEN"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0" 
