image: "rust:latest"

stages:
  - test
  - semgrep

test:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose

semgrep:
  stage: semgrep
  image: semgrep/semgrep
  script: semgrep ci
  rules:
    - if: "$CI_MERGE_REQUEST_IID"
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  variables:
    SEMGREP_APP_TOKEN: "$SEMGREP_APP_TOKEN"